-- The Circle — Supabase schema + seed
-- Изпълни целия файл в Supabase: SQL Editor → New query → Paste → Run

create table if not exists venues (
  id text primary key,
  name text not null,
  type text,
  hood text,
  rating numeric,
  lat double precision,
  lng double precision,
  icon text,
  description text,
  hours text,
  phone text,
  events_count int
);

create table if not exists events (
  id text primary key,
  title text not null,
  cat text,
  venue_id text references venues(id) on delete set null,
  date text,
  day text,
  time text,
  price text,
  free boolean default false,
  featured boolean default false,
  outdoor boolean default false,
  going int default 0,
  interested int default 0,
  description text,
  org_name text,
  org_avatar text,
  grad text
);

-- Включваме Row Level Security
alter table venues enable row level security;
alter table events enable row level security;

-- Всеки може да ЧЕТЕ (публично приложение)
create policy "public read venues" on venues for select using (true);
create policy "public read events" on events for select using (true);

-- Само влезли (logged-in) потребители могат да пишат.
-- За начало, ако ползваш само анонимния ключ от админ панела,
-- размаркирай редовете по-долу, за да позволиш писане с anon ключ:
create policy "anon write venues" on venues for all using (true) with check (true);
create policy "anon write events" on events for all using (true) with check (true);

-- ============ НАЧАЛНИ ДАННИ ============

insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v1','Ancient Theatre','Cultural','Old Town',4.9,42.1469,24.751,'🏛️','The iconic 2nd-century Roman amphitheatre, one of the best-preserved in the world. Hosts opera, concerts, and cultural events under the stars.','09:00–18:00','+359 32 631 353',8) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v2','Kapana Creative District','Nightlife & Culture','Kapana',4.7,42.15,24.748,'🎨','Plovdiv''s vibrant creative quarter packed with galleries, craft bars, street art, and indie shops. The heart of the city''s cultural revival.','Non-stop',NULL,12) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v3','Lucky Pub & Live Music','Concert Hall','Center',4.6,42.143,24.7505,'🎸','Plovdiv''s legendary live music venue hosting rock, jazz, blues, and indie acts every weekend.','19:00–03:00','+359 88 700 1234',6) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v4','Grebna Baza (Rowing Base)','Outdoor Venue','Maritsa',4.5,42.128,24.765,'🚣','Massive outdoor area along the Maritsa river. Home to Hills of Rock and other major festivals.','Open area',NULL,4) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v5','Boris Hristov Cultural Center','Concert Hall','Center',4.7,42.146,24.749,'🎻','Premier cultural venue for classical music, opera, ballet, and theater performances.','10:00–19:00','+359 32 632 269',5) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v6','Cat & Mouse Bar','Bar','Kapana',4.4,42.1498,24.7475,'🍸','Cozy cocktail bar in the heart of Kapana with live jazz nights and craft drinks.','18:00–02:00','+359 89 444 5567',3) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v7','Tsar Simeon''s Garden','Park','Center',4.8,42.147,24.744,'🌳','Plovdiv''s most beloved central park with a singing fountain, playgrounds, and open-air events.','24/7',NULL,5) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v8','City Art Gallery','Gallery','Center',4.5,42.1485,24.746,'🖼️','Houses an impressive collection of Bulgarian art from the Renaissance to contemporary works.','10:00–18:00','+359 32 635 322',4) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v9','OHO Club','Club','Center',4.3,42.1445,24.752,'🎤','Multi-purpose entertainment venue for stand-up comedy, live music, DJ sets, and themed parties.','20:00–04:00','+359 89 333 2211',5) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v10','Youth Hill (Mladejki Halm)','Park & Viewpoint','Center',4.6,42.152,24.753,'⛰️','One of Plovdiv''s famous seven hills with panoramic city views. Perfect for yoga, picnics, and sunset watching.','24/7',NULL,3) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v11','Pavaj Restaurant','Restaurant','Kapana',4.8,42.1495,24.7472,'🍽️','Award-winning restaurant blending traditional Bulgarian cuisine with modern techniques. Set on Kapana''s cobblestone streets.','11:00–23:00','+359 32 260 130',2) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v12','Dada Cultural Bar','Bar & Culture','Kapana',4.5,42.1502,24.7478,'🎷','Art bar with rotating exhibitions, live music, and an eclectic cocktail menu.','17:00–02:00','+359 88 123 4567',4) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v13','Roman Stadium','Historical','Center',4.7,42.1478,24.749,'🏟️','2nd-century Roman stadium stretching beneath the Main Street. One of the largest in the ancient world.','09:30–18:00','+359 32 620 395',2) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v14','Raffy Bar & Gelato','Restaurant & Bar','Center',4.6,42.1465,24.7485,'🍦','Trendy spot on the Main Street famous for artisan gelato, brunch, and evening cocktails.','08:00–00:00','+359 32 623 011',1) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v15','Hebros Hotel Restaurant','Restaurant','Old Town',4.8,42.1475,24.7515,'🏨','Fine dining in a beautifully restored Renaissance house in the Old Town.','12:00–22:00','+359 32 260 180',2) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v16','The Smokehouse','Bar','Kapana',4.3,42.1497,24.7483,'🥃','Whiskey and craft beer bar with a smoky, industrial vibe and weekend DJ sets.','18:00–03:00','+359 89 555 6677',3) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v17','Patchwork Bar','Bar','Kapana',4.4,42.1501,24.7476,'🍺','Eclectic bar with mismatched furniture, board games, and a huge craft beer selection.','16:00–02:00','+359 89 777 8899',2) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v18','Nebet Tepe','Historical & Viewpoint','Old Town',4.8,42.151,24.753,'🌅','The oldest settlement in Plovdiv with ruins dating back 8000 years. Breathtaking sunset views.','24/7',NULL,3) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v19','Bunardjika (Hill of the Liberators)','Park & Monument','Center',4.5,42.144,24.742,'🗽','Home to the Alyosha monument with panoramic views. Popular for jogging and picnics.','24/7',NULL,2) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v20','Sahat Tepe (Clock Hill)','Park & Viewpoint','Center',4.4,42.149,24.754,'🕐','Hill featuring the iconic clock tower, one of Plovdiv''s most recognizable landmarks.','24/7',NULL,1) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v21','Regional Historical Museum','Museum','Old Town',4.6,42.148,24.752,'🏺','Extensive collection covering Plovdiv''s history from Thracian times to the modern era.','09:30–17:30','+359 32 624 339',3) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v22','Ethnographic Museum','Museum','Old Town',4.5,42.1472,24.7518,'🧵','Housed in the stunning Kuyumdzhioglu House, showcasing Bulgarian folk culture and traditions.','09:00–17:00','+359 32 625 654',2) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v23','Plovdiv Regional Library','Cultural','Center',4.3,42.1455,24.747,'📚','Major public library hosting kids workshops, author readings, and educational events.','08:30–20:00','+359 32 622 683',4) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v24','Summer Theatre (Leten Teatar)','Outdoor Stage','Center',4.5,42.1448,24.7445,'🎬','Open-air stage in Tsar Simeon''s Garden for summer concerts, cinema, and theater.','Seasonal',NULL,3) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v25','Dukat Restaurant','Restaurant','Center',4.4,42.1462,24.7488,'🥩','Modern Bulgarian cuisine with an emphasis on locally sourced ingredients and wine pairings.','11:00–23:00','+359 32 266 444',1) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v26','Karamfil Bar','Bar','Center',4.2,42.1458,24.7492,'🌺','Retro-style bar with a laid-back atmosphere, vinyl DJ sets, and affordable drinks.','19:00–03:00','+359 89 111 2233',2) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v27','Plovdiv Fair (Panair)','Exhibition Center','Maritsa',4.3,42.135,24.76,'🏢','International exhibition center hosting trade fairs, expos, and large-scale events.','Event-based','+359 32 902 100',3) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v28','Drama Theatre Plovdiv','Theater','Center',4.6,42.145,24.7495,'🎭','Plovdiv''s main drama theater with a rich repertoire of Bulgarian and international plays.','Box office 10:00–19:00','+359 32 623 073',4) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v29','Philippopolis Art Gallery','Gallery','Old Town',4.4,42.1477,24.7512,'🎨','Contemporary art gallery in a restored Old Town house featuring Bulgarian and international artists.','10:00–19:00','+359 89 222 3344',2) on conflict (id) do nothing;
insert into venues (id,name,type,hood,rating,lat,lng,icon,description,hours,phone,events_count) values ('v30','Markovo Tepe Hill','Park & Viewpoint','Trakia',4.2,42.138,24.762,'🌄','Quiet hill in the Trakia neighborhood, great for trail running and nature walks.','24/7',NULL,1) on conflict (id) do nothing;

insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e1','Hills of Rock 2026','festivals','v4','Jul 24-26','weekend','16:00','89 лв',false,true,true,12400,28500,'Bulgaria''s biggest rock festival returns with international headliners. Three stages, 50+ bands, camping zone, and the best crowd energy in the Balkans.','Hills of Rock Ltd','🎸','linear-gradient(135deg,#E94560,#0F3460)') on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e2','Opera Open — Aida','music','v1','Jun 18','today','21:00','45 лв',false,true,true,3200,8700,'Verdi''s masterpiece performed under the stars at the Ancient Theatre. Full orchestra, stunning set design, and Plovdiv''s most magical cultural night.','State Opera Plovdiv','🎻','linear-gradient(135deg,#F5C518,#E94560)') on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e3','Kapana Fest 2026','festivals','v2','Sep 12-14','weekend','10:00',NULL,true,true,true,8500,21000,'Street art, live music, food stalls, craft beer, and the vibrant energy of Plovdiv''s creative quarter. Three days of non-stop celebration.','Kapana Creative District','🎨','linear-gradient(135deg,#00C9A7,#0F3460)') on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e4','Stand-up Night: Comedy PVD','theater','v9','Today','today','20:30','15 лв',false,false,false,85,240,'Bulgaria''s sharpest stand-up comedians on one stage. Expect unexpected laughs, audience interaction, and zero filter.','Comedy PVD','😂',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e5','Sunrise Yoga on the Hill','outdoor','v10','Tomorrow','tomorrow','06:30',NULL,true,false,true,35,120,'Greet the morning sun with a guided yoga session on Youth Hill. All levels welcome. Bring your own mat.','Plovdiv Yoga Collective','🧘',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e6','Wine Tasting: Thracian Heritage','food','v11','Sat','weekend','18:00','35 лв',false,false,false,28,95,'Explore 6 award-winning wines from the Thracian Valley paired with artisan Bulgarian cheeses and charcuterie.','Plovdiv Wine Society','🍷',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e7','Old Town Night Walk','tours','v1','Fri','weekend','20:00','10 лв',false,false,true,18,65,'Guided evening stroll through Plovdiv''s cobblestone Old Town. Stories of ancient Romans, Bulgarian Revival architecture, and hidden legends.','Plovdiv Free Tours','🚶',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e8','DJ Night: Electronic Kapana','nightlife','v12','Sat','weekend','22:00','20 лв',false,false,false,150,420,'Deep house and techno from local and international DJs. Smoke machines, lasers, and the best sound system in Kapana.','Dada Cultural Bar','🎧',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e9','Kids Art Workshop','kids','v8','Sun','weekend','10:00',NULL,true,false,false,25,80,'Creative painting and collage workshop for children aged 5-12. All materials provided. Parents welcome to join.','City Art Gallery','🖼️',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e10','Plovdiv Running Tour','sports','v7','Sun','weekend','08:00',NULL,true,false,true,45,130,'5K sightseeing run through Plovdiv''s parks, past the Roman Stadium, and along the Main Street. All paces welcome.','Plovdiv Runners Club','🏃',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e11','Jazz Night at Cat & Mouse','music','v6','Thu','today','21:00','12 лв',false,false,false,60,180,'Live jazz trio with craft cocktails. Intimate setting, candlelit tables, and the smoothest grooves in the city.','Cat & Mouse Bar','🎷',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e12','Farmers Market on Glavnata','food','v2','Sat','weekend','08:00',NULL,true,false,true,200,500,'Fresh local produce, organic honey, homemade jams, artisan bread, and handmade crafts every Saturday morning.','Plovdiv Green Market','🥬',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e13','Shakespeare in the Garden','theater','v7','Jun 5','weekend','19:30','20 лв',false,true,true,180,650,'A Midsummer Night''s Dream performed outdoors in Plovdiv''s beloved city garden. Magic, humor, and starlit theater.','Drama Theatre Plovdiv','🎭','linear-gradient(135deg,#7C5CFC,#F5C518)') on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e14','Sunset Photography Walk','tours','v18','Fri','weekend','18:30','15 лв',false,false,true,22,88,'Capture golden hour from Nebet Tepe with a pro photographer guiding composition and camera techniques.','Plovdiv Photo Club','📸',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e15','Craft Beer Festival','food','v2','Aug 8-10','weekend','17:00',NULL,true,true,true,3200,9800,'30+ craft breweries, live music, street food, and the best beer culture Plovdiv has to offer.','Kapana Creative District','🍺','linear-gradient(135deg,#FF9F43,#E94560)') on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e16','Pottery Workshop','workshops','v22','Sat','weekend','14:00','25 лв',false,false,false,12,45,'Hands-on pottery class in the Ethnographic Museum. Make your own ceramic bowl using traditional Bulgarian techniques.','Ethnographic Museum','🏺',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e17','Night of Museums','art','v21','May 18','today','18:00',NULL,true,true,false,5600,15200,'All of Plovdiv''s museums and galleries open for free with special exhibitions, performances, and installations.','Plovdiv Municipality','🏛️','linear-gradient(135deg,#A259FF,#0F3460)') on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e18','Salsa Night','nightlife','v9','Fri','weekend','21:00','10 лв',false,false,false,70,190,'Cuban salsa with a live band. Free beginner lesson at 21:00, social dancing from 22:00. No partner needed.','Plovdiv Salsa Academy','💃',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e19','Book Club: Bulgarian Lit','art','v23','Wed','today','18:30',NULL,true,false,false,15,40,'Monthly discussion group exploring classic and contemporary Bulgarian literature. This month: Aleko Konstantinov.','Plovdiv Regional Library','📚',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e20','Open Air Cinema: Casablanca','theater','v24','Sat','weekend','21:30','8 лв',false,false,true,90,250,'Classic film screening under the stars in the Summer Theatre. Bring a blanket and snacks.','Plovdiv Cinema Club','🎬',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e21','Acoustic Sessions at Patchwork','music','v17','Thu','today','20:00',NULL,true,false,false,40,110,'Unplugged performances by local singer-songwriters. Intimate atmosphere with craft beer on tap.','Patchwork Bar','🎵',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e22','Street Art Tour Kapana','tours','v2','Sun','weekend','11:00',NULL,true,false,true,30,95,'Discover the stories behind Kapana''s most impressive murals and street art pieces with a local artist guide.','Kapana Creative District','🎨',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e23','Trail Run: Seven Hills Challenge','sports','v19','Jun 15','weekend','07:00','25 лв',false,false,true,85,320,'Conquer all seven of Plovdiv''s hills in one epic trail run. 12km, ~400m elevation. Medal for all finishers.','Plovdiv Runners Club','🏃',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e24','Vinyl DJ Set at Karamfil','nightlife','v26','Fri','weekend','22:00',NULL,true,false,false,55,140,'All-vinyl DJ set spinning funk, soul, and disco. Retro vibes and cheap drinks.','Karamfil Bar','🌺',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e25','Kids Science Fair','kids','v23','Sun','weekend','10:00',NULL,true,false,false,60,180,'Interactive science experiments, robotics demos, and a mini planetarium for kids 6-14.','Plovdiv Regional Library','🔬',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e26','Bulgarian Cooking Class','workshops','v15','Sat','weekend','11:00','50 лв',false,false,false,14,55,'Learn to make shopska salata, kavarma, and banitsa with a master chef in a beautiful Old Town setting.','Hebros Hotel','👨‍🍳',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e27','Guided Tour: Roman Plovdiv','oldtown','v13','Daily','today','10:30','15 лв',false,false,true,20,70,'Walk through 2000 years of history — Roman Stadium, Ancient Theatre, Forum, and mosaic floors.','Plovdiv Free Tours','🏛️',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e28','Swing Dance Party','nightlife','v5','Sat','weekend','20:00','15 лв',false,false,false,65,175,'Live swing band + dance floor. Free intro lesson at 20:00, party from 21:00. Dress code: vintage welcome!','Plovdiv Swing Society','🕺',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e29','Contemporary Art Exhibition','art','v29','Ongoing','today','10:00','5 лв',false,false,false,45,120,'New exhibition exploring identity and place through mixed media. 12 Bulgarian and international artists.','Philippopolis Gallery','🎨',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e30','Morning Meditation at Nebet Tepe','outdoor','v18','Daily','today','07:00',NULL,true,false,true,15,50,'Start your day with guided meditation at Plovdiv''s oldest settlement point. Overlooking the entire city.','Plovdiv Mindfulness','🧘',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e31','Plovdiv Jazz Fest','music','v5','Nov 5-8','weekend','19:00','30 лв',false,true,false,1200,4500,'Four nights of world-class jazz at Boris Hristov Cultural Center. International headliners and Bulgarian talent.','Plovdiv Jazz Foundation','🎷','linear-gradient(135deg,#0F3460,#F5C518)') on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e32','Retro Games Night','nightlife','v17','Fri','weekend','19:00',NULL,true,false,false,35,90,'Board games, retro video games, and trivia night. Pizza and drinks available. Bring your crew.','Patchwork Bar','🎮',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e33','Organic Brunch Market','food','v7','Sun','weekend','09:00',NULL,true,false,true,150,380,'Artisan coffee, fresh pastries, organic produce, and live acoustic music in Tsar Simeon''s Garden.','Plovdiv Green Market','☕',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e34','Theatre: Под игото','theater','v28','Fri','weekend','19:00','18 лв',false,false,false,120,350,'Ivan Vazov''s classic novel adapted for the stage. A powerful exploration of Bulgarian identity and freedom.','Drama Theatre Plovdiv','🎭',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e35','Sketching in the Old Town','workshops','v21','Sat','weekend','10:00','20 лв',false,false,true,18,60,'Urban sketching workshop — capture Plovdiv''s Revival architecture with pen and watercolor. All skill levels.','Plovdiv Art Studio','✏️',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e36','Capoeira in the Park','sports','v7','Sat','weekend','17:00',NULL,true,false,true,20,65,'Brazilian martial art meets dance. Open roda (circle) in Tsar Simeon''s Garden. Beginners welcome.','Plovdiv Capoeira Group','🤸',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e37','Night of the Ancient Theatre','oldtown','v1','Jun 21','weekend','20:30',NULL,true,false,true,2500,7000,'Special summer solstice event — the Ancient Theatre lit by torchlight with music and theatrical performances.','Plovdiv Municipality','🔥',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e38','Tech Meetup Plovdiv','workshops','v9','Wed','today','18:30',NULL,true,false,false,55,160,'Monthly tech community meetup. This month: AI in daily life. Networking, talks, and free pizza.','PlovdivTech','💻',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e39','Flamenco Night','music','v12','Thu','today','21:00','15 лв',false,false,false,45,130,'Live flamenco guitar and dance performance. Tapas menu available. Transport yourself to Andalusia.','Dada Cultural Bar','💃',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e40','Family Treasure Hunt','kids','v1','Sun','weekend','10:00','12 лв',false,false,true,35,100,'Explore the Old Town solving clues and discovering hidden gems. Fun for ages 5+. Prize for every team.','Plovdiv Adventures','🗺️',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e41','Sunset Cocktails at Nebet Tepe','food','v18','Fri-Sat','weekend','19:00','8 лв',false,false,true,80,220,'Pop-up cocktail bar on Nebet Tepe every Friday and Saturday. Watch the sunset over Plovdiv with a drink in hand.','Nebet Tepe Bar','🍹',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e42','Plovdiv Marathon 2026','sports','v7','Oct 12','weekend','08:00','40 лв',false,true,true,2800,8200,'Full marathon, half marathon, and 10K through Plovdiv''s streets and parks. Run past 8000 years of history.','Plovdiv Sports Federation','🏅','linear-gradient(135deg,#00C9A7,#0F3460)') on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e43','Indie Film Screening','theater','v24','Wed','today','20:00','5 лв',false,false,true,30,75,'Weekly screening of independent Bulgarian and European cinema at the Summer Theatre.','Plovdiv Cinema Club','🎥',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e44','Whiskey Tasting Evening','food','v16','Sat','weekend','20:00','40 лв',false,false,false,18,55,'Guided tasting of 5 premium single malts paired with dark chocolate and cigars.','The Smokehouse','🥃',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e45','Morning Tai Chi','outdoor','v19','Daily','today','07:30',NULL,true,false,true,12,40,'Gentle tai chi practice on Bunardjika hill. All levels welcome. Meet at the Alyosha monument.','Plovdiv Tai Chi','☯️',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e46','Improv Comedy Show','theater','v9','Sat','weekend','20:00','12 лв',false,false,false,75,200,'Unscripted comedy where the audience drives the show. Every performance is unique.','Plovdiv Improv','🤡',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e47','Calligraphy Workshop','workshops','v8','Sun','weekend','14:00','30 лв',false,false,false,10,35,'Learn the art of Cyrillic calligraphy. Create your own personalized artwork to take home.','City Art Gallery','✒️',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e48','Bike Tour: Parks & Hills','tours','v7','Sat','weekend','09:00','20 лв',false,false,true,16,55,'Guided 15km bike ride through Plovdiv''s parks and hill viewpoints. Bike rental included.','Plovdiv Bike Tours','🚲',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e49','Opera Open — Carmen','music','v1','Jul 2','weekend','21:00','45 лв',false,false,true,2800,7500,'Bizet''s Carmen at the Ancient Theatre. Passion, drama, and some of opera''s most famous arias.','State Opera Plovdiv','🎻',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e50','Handmade Market','art','v2','Sun','weekend','10:00',NULL,true,false,true,120,350,'Local artisans selling jewelry, ceramics, prints, textiles, and more in the heart of Kapana.','Kapana Creative District','💍',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e51','Electronic Music Festival','festivals','v4','Aug 22-23','weekend','18:00','55 лв',false,false,true,4200,12000,'Two-day electronic music festival at Grebna Baza. Techno, house, drum & bass across 3 stages.','Plovdiv Beats','🎧',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e52','Dog Friendly Picnic','outdoor','v7','Sun','weekend','11:00',NULL,true,false,true,40,120,'Bring your pup for a community picnic. Dog treats, games, and a mini agility course.','Plovdiv Dog Lovers','🐕',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e53','Tango Milonga','nightlife','v5','Sun','weekend','19:00','10 лв',false,false,false,40,110,'Traditional Argentine tango evening. Cortinas, tandas, and elegant dancing in a beautiful venue.','Plovdiv Tango Club','💃',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e54','Scene at the Crossroad','festivals','v1','Sep 18-22','weekend','19:00','30 лв',false,true,true,3500,11000,'International theater festival at the Ancient Theatre and venues across the Old Town.','Scene at the Crossroad Foundation','🎭','linear-gradient(135deg,#FF6B6B,#7C5CFC)') on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e55','Smoothie & Acai Bowl Pop-Up','food','v14','Sat-Sun','weekend','09:00','9 лв',false,false,false,30,85,'Weekend-only tropical smoothie and acai bowl bar at Raffy. Fresh, colorful, and Instagram-ready.','Raffy Bar & Gelato','🥤',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e56','Astronomy Night','outdoor','v20','Fri','weekend','22:00',NULL,true,false,true,25,70,'Telescope stargazing from Sahat Tepe with the Plovdiv Astronomy Club. Jupiter and Saturn visible this month.','Plovdiv Astronomy Club','🔭',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e57','Thracian Gold Exhibition','oldtown','v21','Ongoing','today','10:00','10 лв',false,false,false,350,900,'Replicas and originals of Thracian gold treasures. The Panagyurishte treasure and more.','Regional Historical Museum','👑',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e58','Live Painting Performance','art','v12','Fri','weekend','20:00',NULL,true,false,false,35,95,'Watch an artist create a large-scale painting live, accompanied by electronic music.','Dada Cultural Bar','🎨',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e59','Kids Puppet Theatre','kids','v28','Sun','weekend','11:00','8 лв',false,false,false,55,140,'Classic fairy tale puppet show for ages 3-10. Interactive, funny, and magical.','Drama Theatre Plovdiv','🧸',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e60','Plovdiv Food Fest','festivals','v7','Oct 4-6','weekend','11:00',NULL,true,false,true,6000,18000,'Three days of culinary excellence in Tsar Simeon''s Garden. 50+ restaurants, cooking demos, and tastings.','Plovdiv Municipality','🍴',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e61','Alyosha Hill Sunset Run','sports','v19','Wed','today','18:30',NULL,true,false,true,25,70,'Casual 3K sunset run up Bunardjika. Meet at the base, finish at the monument. All levels.','Plovdiv Runners Club','🏃',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e62','Wine & Paint Night','workshops','v6','Thu','today','19:00','35 лв',false,false,false,16,50,'Sip wine and paint a Plovdiv cityscape. No experience needed — all materials and 2 glasses included.','Cat & Mouse Bar','🎨',NULL) on conflict (id) do nothing;
insert into events (id,title,cat,venue_id,date,day,time,price,free,featured,outdoor,going,interested,description,org_name,org_avatar,grad) values ('e63','International Trade Fair','workshops','v27','May 25-30','weekend','10:00','5 лв',false,false,false,3500,8500,'Plovdiv''s biggest trade exhibition with hundreds of exhibitors from across Europe.','Plovdiv Fair','🏢',NULL) on conflict (id) do nothing;
